### ISSUE TITLE
Open file on result line

### ISSUE THREAD

**Issue by filipkaras** [visualgrep/app#17]
I'm using VisualGrep to find variables, functions, etc... in PHP files. It's great that I can open the file in my editor (SublimeText) directly by clicking the file in VisualGrep, however, it would be awesome if 2 small features will be added:
1. Open the file on the line the result was found.
2. Open the file in the same instance of editor (now it always open new window)

**Comment by dafi** [comment]
Please refer to wiki documentation at 

https://github.com/visualgrep/app/wiki/Editors-Integration
