### ISSUE TITLE
Launch through CLI like VisualAck

### ISSUE THREAD

**Issue by ghost** [visualgrep/app#18]
Like many developers, I'm working many times through iTerm2 (or just the standard Terminal), so I'd really like if launching VisualGrep through the CLI was possible, in the same way that VisualAck allows this.

**Comment by dafi** [comment]
Creating a UI frontend is a good idea, I don't agree with an application outputting result to stdout (eg terminal output)

**Comment by ghost** [comment]
Yeah, launching VisualGrep through the CLI is what's really useful... I haven't had any need to output to stdout.

**Comment by dafi** [comment]
Implemented on version 1.2.3 (funny version number), it will be submitted to MAS in a couple of days

**Comment by dafi** [comment]
Just for completeness you can find the documentation [here](https://github.com/visualgrep/app/wiki/CommandLine-Support)

**Comment by ghost** [comment]
Thank you so much for this, Davide!

BTW, has VisualGrep been featured in Mac AppStorm, MacWorld Gems, Mac Power Users, and One Thing Well?

...Consider sending an introduction email to each one of these... (Probably it's better after this 1.2.3 update...) VisualGrep sure deserves more exposure. :)

**Comment by dafi** [comment]
Honestly I don't think they are interested to review a little utility like VisualGrep but ASAP I'll try to contact them.

I hope Apple reviews quickly v1.2.3

**Comment by ghost** [comment]
All of those I've mentioned, they also talk about small utilities. There's also brettterpstra.com -- he does the Systematic podcast, where he talks (at the end) about small utilities as well.

The best to you, Davide.

**Comment by dafi** [comment]
Oh I didn't know brettterpstra.com, I will try to contact them, too.

Thanks for your feedback :)

**Comment by ghost** [comment]
That's Brett Terpstra's blog. He does the Systematic podcast -- http://5by5.tv/systematic

He is also the author of Marked -- http://markedapp.com/

For Mac AppStorm, try contacting Pedro Lobo (the main reviewer there, I guess), here's his blog -- http://palobo.tumblr.com/

> Thanks for your feedback :)

You're welcome, Davide :) Hope it helps!

**Comment by ghost** [comment]
Davide,

This CLI access feature means that VisualGrep will become my main text file search utility. So I'll be making a few more feature requests... ;)

I'll open separate issue tickets for each one of them...

**Comment by dafi** [comment]
Feel free to submit any request, at this time I'm working on VisualDiffer (the other my little creature) but I want to enhance VisualGrep, too

**Comment by ghost** [comment]
Yeah, I also own VisualDiffer. :)

Thanks.

**Comment by dafi** [comment]
Finally I've submitted VG with command line support, it was a pain due to sandboxing, Apple requires every binary must be sandboxed but this breaks IPC communication and the helper tool need IPC to communicate with main .app.

Please when VG will be approved (I hope a couple of weeks if Apple doesn't find problems), test it so I can close this bug

**Comment by ghost** [comment]
> Please when VG will be approved (I hope a couple of weeks if Apple doesn't find problems), test it so I can close this bug

I will! :)

Thanks Davide.

**Comment by dafi** [comment]
VisualGrep with CLI support is available on MAS

**Comment by ghost** [comment]
Thank you, Davide. Do you want me to test the CLI interface thoroughly, or just its basic functionality? If it's thoroughly (like, every CLI parameter), then I will be able to test it in about 4-5 hours...

**Comment by dafi** [comment]
Just if it works as you need/expect :)

**Comment by ghost** [comment]
Davide, these 2 days have been really busy... I'll go out now for a couple of hours to get some fresh air... And I'll test it first thing when I get back :)

**Comment by dafi** [comment]
Andre, don't worry you have helped me very much with many useful hints.
Feel free to test VG when possible, next week, next month, really don't worry :)

I'm working to the search on multiple paths so maybe I can submit another version and you will be able to test the next version (I think this will require two/three weeks)

thanks for your feedback

**Comment by ghost** [comment]
It's working fine for searches like these:
- visgrep toInteger
- visgrep .. toInteger
- visgrep .. toInteger --wait

I'll now create a template and test that part... :)

**Comment by ghost** [comment]
> I'm working to the search on multiple paths

Sure, I'll test this too when it comes out :)

**Comment by ghost** [comment]
Working fine too:
- visgrep -t js .. toInteger --wait

Thank you very much for adding CLI access, Davide! :)

**Comment by ghost** [comment]
If you need something more to be tested, let me know...

**Comment by dafi** [comment]
Thanks!!!

Now I can close this bug
