### ISSUE TITLE
Question: A Template for each Folder Project?

### ISSUE THREAD

**Issue by ghost** [visualgrep/app#19]
Davide, if I have several projects (say, programming projects), each one in a folder... Is creating a Template for each the best way to go?

...My goal is to easily (and quickly) search for a piece of text (say "todo: ") in each one of them at each time.

**Comment by dafi** [comment]
Maybe adding the ability to specify many directories where to search is _the_ solution.

If the search can traverse multiple directories you can save the template for "group"

**Comment by ghost** [comment]
> Maybe adding the ability to specify many directories where to search is the solution.

Yes, this would make sense. Because then I could setup only one criteria / filter for all projects of the same kind.

**Comment by dafi** [comment]
I'm realizing only now this is a terrific improvement, why I have not thought about it before...
I hope to starting working to it very soon

**Comment by ghost** [comment]
That's great! :) Thank you, Davide.

**Comment by dafi** [comment]
Thanks to you for feedback.

This feature requires a bit of work but I really need it for myself so its priority is 'urgent'

**Comment by dafi** [comment]
Just a preview of Multi Paths Search, obviously the height can be changed from user and by default is only two lines tall
Search order can be changed dragging paths in preferred order

![multiplepaths](https://f.cloud.github.com/assets/84500/519355/d6754a84-bf14-11e2-8548-c628535f295a.png)

**Comment by ghost** [comment]
Wow! This is wonderfully implemented! :)

Is each path's text directly editable? (Or would this take too much work to implement?)

**Comment by dafi** [comment]
No, paths can't be edited by design.
This because any path must be "validated" by powerbox (eg the Apple sandbox) so if user edits the path to a parent then everything works fine but if he/she types a not already-open-from-dialog-or-dragged path then an alert box warns users to select the path from open dialog.

Current VG allows to edit path but suffers of this ugly behaviour, so I've decided to redesign the path list

**Comment by ghost** [comment]
> Current VG allows to edit path but suffers of this ugly behaviour, so I've decided to redesign the path list

OK. So we can just double click on a path (in the list) and the folder selection dialog comes up? Is that it?...

**Comment by dafi** [comment]
> OK. So we can just double click on a path (in the list) and the folder selection dialog comes up? Is that it?...

Yes

**Comment by ghost** [comment]
OK. Seems good to me :)
