### ISSUE TITLE
Choose between regex or literal searching

### ISSUE THREAD

**Issue by ghost** [visualgrep/app#20]
Is VisualGrep doing regex or literal text searches?  Having a setting (say, before the "Search on subfolder" one) for toggling between each, would be very useful.

**Comment by dafi** [comment]
Actually user can choose regex/literal from the first popover, do you mean moving this selection in another place?

**Comment by ghost** [comment]
Where is that, presently? Can you attach a screenshot here please?

**Comment by ghost** [comment]
You're talking about version 1.2.2, right?

**Comment by dafi** [comment]
Yes v1.2.2, this feature is present from v1.0, I can't live without it

![regexp](https://f.cloud.github.com/assets/84500/467214/6616603e-b672-11e2-8edb-5571b8a5fd06.png)

**Comment by ghost** [comment]
Ah, I see now! :) Yes, the present location is not very intuitive... Because one thinks that icon is about the Searching on subfolders option...

**Comment by dafi** [comment]
Maybe is intuitive only for me... I need to rethink about it

**Comment by ghost** [comment]
Ok, after looking at the popups carefully, I understand how the UI works...

You know, adding a "heading" at the beginning of each setting's result, would help to understand the UI...

You could add, for each settings' visual row, these headings:
- General Settings: 
- Include Settings: 
- Exclude Settings: 

And only these headings would be in bold.

So, the first setting row would be something like:
[checkbox] [icon] *_General Settings: *_ Search on subfolders. Skip packages

And the second row:
[checkbox] [icon] *_Include Settings: *_ No include filters, all files and folders will be searched

EDIT: The "**" means bold. I'm not sure why this Markdown is not being displayed here.

..And similar for the third row, of course.

Do you see what I mean, Davide?  What do you think?

**Comment by dafi** [comment]
Something like this?
![newui2](https://f.cloud.github.com/assets/84500/467323/733a8246-b676-11e2-87ba-4e5f17f74329.png)

Or like this, the height increases too much for my personal taste
![newui](https://f.cloud.github.com/assets/84500/467299/d444d970-b675-11e2-841a-677f976ec45e.png)

**Comment by ghost** [comment]
Yes, the first case. :)

**Comment by ghost** [comment]
...Agree with not increasing the height. :) That's something that bothers me in many apps' UIs.

**Comment by ghost** [comment]
Maybe the "Settings" text could even be omitted?

**Comment by dafi** [comment]
Yes, so the string is shorter

**Comment by ghost** [comment]
And, in keeping with the present UI "strategy", maybe you would prefer switching the "bold" to the settings' result text (that comes after each heading)... So, just adding the heading text without bold.

To look at a prototype does help a lot. :)

**Comment by dafi** [comment]
I like the UI shown below, what do you think?
![newui](https://f.cloud.github.com/assets/84500/469805/d9ab9a50-b6e0-11e2-8103-273ba866c80a.png)

**Comment by ghost** [comment]
I like it! Looks great :)
