### ISSUE TITLE
Add common minified files to default exclude filter (minified css and js files)

### ISSUE THREAD

**Issue by ghost** [visualgrep/app#21]
Davide, it would make sense to add these to the exclusion filter by default:
- .min.css
- .min.js

(Like ack 2 does.)

**Comment by dafi** [comment]
mmm  I don't agree.

Predefined installed filters must be as agnostic as possible.
java developers should want `.class` as default, web developers minified versions, c/c++ devs `.o`

Actually user can set its own application default but maybe the process to do this is really complicated (i.e. UI fails)

Take a look at picture shown below
![filters](https://f.cloud.github.com/assets/84500/469832/e66781c2-b6e1-11e2-907e-eb444cfa91cb.png)

**Comment by ghost** [comment]
OK... I think that the UI is pretty good... It's kind of tucked away... But, anyway, that command ("Set Current as Defaults") would not be used frequently, so I think that it is OK in that place...

BTW:
- Why is "Add Row" needed, if there are already the + icons to do that in the right position?
- What's the difference between "Fill with Defaults" and "Restore Defaults"?

**Comment by dafi** [comment]
"Add row" is a dirty workaround for a bug on cocoa PredicateEditor, if you delete all filters the + icon disappears for ever, you cannot add a new one but if you add a new row then you can restart.

"Fill with Defaults"  replace the current filter with the defined defaults
"Restore Defaults" restore the installation default

**Comment by ghost** [comment]
OK, then "Restore Defaults" should be "Restore Factory Defaults" to avoid misunderstandings.

**Comment by dafi** [comment]
Oh yes, you are right!!
