### ISSUE TITLE
New Global Preference: Disable Save dialog on window closing when search is launched from CLI

### ISSUE THREAD

**Issue by ghost** [visualgrep/app#24]
This would be useful too.

**Comment by dafi** [comment]
This is a bug, indeed opening VG from Finder service menu the document doesn't ask to save if settings are not changed

**Comment by dafi** [comment]
Fixed in v1.2.4.
I've not added any UI to change behavior becuause this is a very super-mega-advanced choice so it will available from terminal setting value using the `defaults` command

Now by default closing document doesn't ask to save

**Comment by ghost** [comment]
> Now by default closing document doesn't ask to save

Great! Thanks, Davide.
