### ISSUE TITLE
VisualGrep search function terminates after second search

### ISSUE THREAD

**Issue by f14bdriver** [visualgrep/app#26]
Hello,

I have version 1.2.5 installed on Yosemite 10.10.1  Upon launching the Visual Grep program, I can perform a search with results.  When I try to perform another search using different parameters, the program crashes with a summary of the panic, asking to send to Apple.  I have captured this information in a text file and can send to you for examination.  Do you need any other logs to review?

**Comment by dafi** [comment]
Hi,

send me the text file and take a look at console output just after log, to see the console log run the application console.app.
Thanks for your feedback

**Comment by f14bdriver** [comment]
Here are the logs per your request.

**Comment by dafi** [comment]
I forgot github doesn't allow attachments...

Please may you send the files to 
There is a crash log at   `/Users/benedictouano/Library/Logs/DiagnosticReports/VisualGrep_2014-12-28-231931_Benedicts-MacBook-Pro.crash` you can see it from console.app 

BTW You can delete all VisualGrep settings and start from a clean env, you can delete manually all files contained into ~/Library/Containers/com.visualgrep\* or you can use the free app http://www.freemacsoft.net/appcleaner/ and remove everything _except_ the VisualGrep app
