### ISSUE TITLE
Customize search tools

### ISSUE THREAD

**Issue by hongxuchen** [visualgrep/app#27]
I don't know the mechanism of visualgrep, but I do hope there is an option that customizes the grep tool (at least it should officially support external tools like `GNU grep`, [ack](https://github.com/petdance/ack) and [the silver searcher](https://github.com/ggreer/the_silver_searcher)).

**Comment by dafi** [comment]
VG isn't a command line tool wrapper but it uses only its own implementation but any idea is welcomed.
