### ISSUE TITLE
How to use templates?

### ISSUE THREAD

**Issue by sharmashivanand** [visualgrep/app#28]
The official screenshot of VisualGrep on your site shows several templates in the left sidebar. What is a template? How do I create and save one? Is there are way to enable regex search by default? I'm a coder and everytime I have to search I have to go in and check that box to enable regexes. Is there a default way to set it to checked?

**Comment by dafi** [comment]
To create a template
1. setup your search settings (regexp, filters, search folders)
2. click on the '+' sign on left bottom corner
3. enter the template name (eg 'html and css')
4. the template will appear on the left

To use the template, click on it and all settings will be used
![templates](https://cloud.githubusercontent.com/assets/84500/8694428/36731776-2adf-11e5-896c-a73e2edc931e.jpg)

Flags are not stored, this is a bug, please apologize me.
At this time the only way to quickly reuse settings is to use templates.

**Comment by sharmashivanand** [comment]
Hi Dafi,

Thanks for your response. What are flags? You mean checkboxes?

**Comment by dafi** [comment]
Yes, every checkbox value isn't store

**Comment by sharmashivanand** [comment]
By the way when I right click a folder to grep and then select the template, it clears the folder path set in "Search in  Folders" at the very top.

Is there a way to have the template retain the same path as was already there when I right click on the folder to grep?

**Comment by dafi** [comment]
"Right click" where? Do you mean in Finder?

**Comment by sharmashivanand** [comment]
Yes, finder.

**Comment by dafi** [comment]
The path is always overwritten but your idea sounds very smart I want to implement it "if path is empty then use the path (if any) present on template, else doesn't overwrite"
I think to publish a new version in few days and add this feature to it

**Comment by sharmashivanand** [comment]
Awesome!!! :)

**Comment by dafi** [comment]
I will implement it as a user setting so I don't break the current behavior, you must explicitly set the "Ignore Template Search Paths if already present" flag

See #29

**Comment by sharmashivanand** [comment]
Thanks so much for the update. This fixes it :)

**Comment by dafi** [comment]
Thanks to you, now I close the issue. Feel free to reopen it or a new one if necessary
