### ISSUE TITLE
Templates don't save folders

### ISSUE THREAD

**Issue by tpaine** [visualgrep/app#31]
Perhaps I'm not using the product as intended but I like to use templates to limit my searches to certain folders. I have one for each client so I can search only their files. The problem is that switching between templates doesn't change which folders to search in. It also only seems to save the folders for one of my templates.

I'm running version 1.2.7

**Comment by dafi** [comment]
Version 1.2.7 introduces the ability to "ignore" the search folders (see #29 ) but this option can be turned off.
Open Preferences Panel and change the option `Preserve the 'Search in Folders' value` if this doesn't work there is a bug

**Comment by tpaine** [comment]
Turning that setting off had no effect. I've actually had this issue for a while. I created a template when I first purchased the program (Nov,\* 2013) to search certain folders, but any subsequent templates I created would not save the folders. I just tried a few things to resolve it to no avail including reinstalling the app and deleting all my templates. Now when I create a new template, add folders, quit the app and come back the "search in folders" field is empty.

Perhaps there is some problem with my install? How to I complete remove the app? I tried using Clean My Mac to uninstall VisualGrep but when I reinstalled it from the App Store my old templates were still there.

**Comment by dafi** [comment]
Templates are stored into
`/Users/<<your user name>>/Library/Containers/com.visualgrep/Data/Library/Templates/`

Thy to delete (or rename) the file `Default.vgtemplates`

**Comment by dafi** [comment]
I forget to ask to you if you can send me your `Default.vgtemplates` file,  It's a `plist` (ie `xml`) but if it contains private info don't send to me

**Comment by tpaine** [comment]
Ok here is the file but deleting has not fixed my issue.

**Comment by dafi** [comment]
Please apologize but github doesn't allow attachments, please send the file to ``

May you see if the `console.app` contains some log info about the bug? I've tried to reproduce it but without success
