### ISSUE TITLE
How to use regex to search

### ISSUE THREAD

**Issue by dreamchaser123** [visualgrep/app#34]
Dear sir, I wanna use regex to search in the text file.How can I do this?

**Comment by dafi** [comment]
The example shown below should help
![visualgrep_regexp](https://user-images.githubusercontent.com/84500/36031509-44a3299c-0dab-11e8-934f-b2dafde179f9.png)

**Comment by dreamchaser123** [comment]
@dafi Got it, thank you~! I‘ve got to say your app is totally amazing!

**Comment by dafi** [comment]
thanks for using it :)

**Comment by dreamchaser123** [comment]
<img width="137" alt="screen shot 2018-02-10 at 15 10 35" src="https://user-images.githubusercontent.com/26835325/36059524-eaa1ab42-0e74-11e8-9076-22ba8215d649.png">
How can I know about the context of the previous line 343103?or the following line 343105?

**Comment by dafi** [comment]
No context lines are shown

**Comment by dreamchaser123** [comment]
Well, sorry, I mean the content line

**Comment by dreamchaser123** [comment]
<img width="390" alt="screen shot 2018-02-11 at 14 08 31" src="https://user-images.githubusercontent.com/26835325/36070415-19250764-0f35-11e8-9c52-06d04c590e78.png">
I mean how can I know about the previous content line?

**Comment by dafi** [comment]
VG shows only the line containing the match, you can only see whole file opening in editor or with spotlight

**Comment by dreamchaser123** [comment]
Alright,thank you

**Comment by PhilipSharman** [comment]
Hmm ... I don't see that "RegEx" option.  (I'm using version 1.2.8, which I believe is the latest.)  Was the option removed, or am I missing something?  Thanks.

![image](https://user-images.githubusercontent.com/209361/40850156-1c206d12-6581-11e8-83d7-84bbbc34f17a.png)

**Comment by PhilipSharman** [comment]
D'oh! Never mind.  I found it. (For anyone else with the same question, it is in the "Search for subfolders" option.  I never thought of looking in there.)
