### ISSUE TITLE
add preference to suppress the audio notification

### ISSUE THREAD

**Issue by s-diniro** [visualgrep/app#35]
Love the app! thank you

One request for a small enhancement. Can you add an option in the preferences to suppress the audio cue that is played when the grep is done? thx

**Comment by dafi** [comment]
Hi,

you can turn off the sound from System Notification panel

1. Open System Preferences from the Apple menu (not the visual grep menu but the mac system menu)
2. Click the notifications icon
3. On the left select VisualGrep and uncheck the button

Something like this
![macos-high-sierra-system-preferences-notifications-calendar-alerts](https://user-images.githubusercontent.com/84500/47603988-f4138380-d9f3-11e8-9a92-2bea664f2c65.jpg)

**Comment by s-diniro** [comment]
I did _not_ know about this global preference after all these years on macOS!

Thanks for the tip, and thanks for the prompt reply. Closing.......
