### ISSUE TITLE
V. 1.8.9: Not All Text Shown In Preferences → Confirmations

### ISSUE THREAD

**Issue by Spoekenkieker** [visualgrep/app#47]
The “Confirmations” panel in Preferences doesn’t show all text for point “Include Filtered Items By Default”, see screenshot.

To reproduce: Open Preferences, click “Confirmations”, see below “Include Filtered Items By Default”.

It is neither possible to make the window bigger nor to scroll, thus only the top few pixels of the next text line are visible.

<img width="754" alt="image" src="https://github.com/visualgrep/app/assets/7978735/22135c1d-a74f-45ad-8d91-419fc7949b09">

**Comment by dafi** [comment]
This is the issue channel for VisualGrep, but no problem ;)

Confirmed the bug on https://visualdiffer.com/mantis/view.php?id=367

**Comment by Spoekenkieker** [comment]
Oh, sry, forgive my confusion 😅 and thx!
